export const beekeepingData = {
  "3a": {
    january: [
      {
        title: "Deep Winter Management",
        description: "Bees are in tight cluster. Minimal disturbance required.",
        difficulty: "beginner",
        timeEstimate: "15 minutes per apiary",
        tips: [
          "Only check on days above 20°F (-7°C)",
          "Listen for buzzing without opening hive",
          "Clear snow from entrances",
          "Check hive weight by lifting back corner",
        ],
      },
      {
        title: "Equipment Preparation",
        description: "Prepare equipment for spring while bees are dormant.",
        difficulty: "beginner",
        timeEstimate: "2-3 hours per week",
        tips: [
          "Clean and repair equipment in heated space",
          "Order replacement parts early",
          "Build new equipment if needed",
          "Plan for late spring start (May-June)",
        ],
      },
    ],
    february: [
      {
        title: "Emergency Feeding Check",
        description: "Monitor food stores during coldest period.",
        difficulty: "beginner",
        timeEstimate: "20 minutes per hive",
        tips: [
          "Check only on days above 25°F (-4°C)",
          "Use fondant or winter patties if needed",
          "Avoid liquid feeding in extreme cold",
          "Monitor for starvation signs",
        ],
      },
      {
        title: "Order Bees & Supplies",
        description: "Order bees for late spring arrival.",
        difficulty: "beginner",
        timeEstimate: "1-2 hours",
        tips: [
          "Order packages/nucs for May-June delivery",
          "Plan for short but intense season",
          "Order extra honey supers",
          "Consider local suppliers for hardier stock",
        ],
      },
    ],
    march: [
      {
        title: "Late Winter Assessment",
        description: "Check colony survival as temperatures begin to warm.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Wait for consistent 40°F (4°C) temperatures",
          "Check for live bees and food stores",
          "Begin feeding if stores are low",
          "Plan for April-May first inspection",
        ],
      },
    ],
    april: [
      {
        title: "Pre-Spring Preparation",
        description: "Prepare for late spring start.",
        difficulty: "beginner",
        timeEstimate: "1-2 hours per apiary",
        tips: [
          "Clean bottom boards",
          "Remove winter wraps gradually",
          "Prepare feeding equipment",
          "Monitor for late frosts",
        ],
      },
    ],
    may: [
      {
        title: "First Spring Inspection",
        description: "Begin active beekeeping season.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Check for queen and brood",
          "Assess food stores",
          "Begin stimulative feeding",
          "Add second brood box if needed",
        ],
      },
      {
        title: "Install New Bees",
        description: "Install packages or nucs.",
        difficulty: "beginner",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Install on warm, calm days",
          "Provide immediate feeding",
          "Check for queen acceptance",
          "Monitor for 7-10 days",
        ],
      },
    ],
    june: [
      {
        title: "Colony Building",
        description: "Support rapid colony development.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor brood pattern",
          "Add honey supers early",
          "Check for queen cells",
          "Begin swarm prevention",
        ],
      },
    ],
    july: [
      {
        title: "Peak Season Management",
        description: "Manage honey production and prevent swarming.",
        difficulty: "beginner",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Add supers as needed",
          "Check for queen cells weekly",
          "Monitor honey flow",
          "Consider making splits",
        ],
      },
    ],
    august: [
      {
        title: "Honey Harvest Preparation",
        description: "Prepare for harvest and winter preparation.",
        difficulty: "beginner",
        timeEstimate: "1 hour per hive",
        tips: [
          "Harvest honey when capped",
          "Leave adequate stores (80-100 lbs)",
          "Treat for varroa mites",
          "Begin winter preparation",
        ],
      },
    ],
    september: [
      {
        title: "Winter Preparation",
        description: "Prepare colonies for long winter.",
        difficulty: "beginner",
        timeEstimate: "1 hour per hive",
        tips: [
          "Ensure adequate honey stores",
          "Reduce hive entrances",
          "Add mouse guards",
          "Check queen status",
        ],
      },
    ],
    october: [
      {
        title: "Final Winter Prep",
        description: "Complete winter preparations.",
        difficulty: "beginner",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Remove excess supers",
          "Add insulation if needed",
          "Secure hives from wind",
          "Final varroa treatment",
        ],
      },
    ],
    november: [
      {
        title: "Winter Setup",
        description: "Complete winter setup and monitoring.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per apiary",
        tips: [
          "Check hive weight",
          "Listen for buzzing",
          "Clear entrances of debris",
          "Monitor for mice",
        ],
      },
    ],
    december: [
      {
        title: "Winter Monitoring",
        description: "Minimal monitoring during deep winter.",
        difficulty: "beginner",
        timeEstimate: "15 minutes per apiary",
        tips: [
          "Check only on warm days",
          "Listen for colony activity",
          "Clear snow from entrances",
          "Plan for spring",
        ],
      },
    ],
  },
  "4a": {
    january: [
      {
        title: "Deep Winter Management",
        description: "Bees are in tight cluster. Minimal disturbance required.",
        difficulty: "beginner",
        timeEstimate: "15 minutes per apiary",
        tips: [
          "Only check on days above 25°F (-4°C)",
          "Listen for buzzing without opening hive",
          "Clear snow from entrances",
          "Check hive weight by lifting back corner",
          "Monitor for wind protection",
        ],
      },
      {
        title: "Equipment Preparation",
        description: "Prepare equipment for spring while bees are dormant.",
        difficulty: "beginner",
        timeEstimate: "2-3 hours per week",
        tips: [
          "Clean and repair equipment in heated space",
          "Order replacement parts early",
          "Build new equipment if needed",
          "Plan for late spring start (May-June)",
          "Prepare winter wraps for next season",
        ],
      },
      {
        title: "Winter Mite Treatment (Oxalic Acid)",
        description: "Treat for varroa mites monthly using oxalic acid vaporization.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Only use oxalic acid vaporization",
          "Treat on days above 35°F (2°C)",
          "Do not open hive - use vaporizer",
          "Follow safety protocols",
          "Monitor treatment effectiveness",
        ],
      },
    ],
    february: [
      {
        title: "Emergency Feeding Check",
        description: "Monitor food stores during coldest period.",
        difficulty: "beginner",
        timeEstimate: "20 minutes per hive",
        tips: [
          "Check only on days above 25°F (-4°C)",
          "Use fondant or winter patties if needed",
          "Avoid liquid feeding in extreme cold",
          "Monitor for starvation signs",
          "Check cluster position",
        ],
      },
      {
        title: "Order Bees & Supplies",
        description: "Order bees for late spring arrival.",
        difficulty: "beginner",
        timeEstimate: "1-2 hours",
        tips: [
          "Order packages/nucs for May-June delivery",
          "Plan for short but intense season",
          "Order extra honey supers",
          "Consider local suppliers for hardier stock",
          "Order winter protection supplies early for next season",
        ],
      },
      {
        title: "Winter Mite Treatment (Oxalic Acid)",
        description: "Treat for varroa mites monthly using oxalic acid vaporization.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Only use oxalic acid vaporization",
          "Treat on days above 35°F (2°C)",
          "Do not open hive - use vaporizer",
          "Follow safety protocols",
          "Monitor treatment effectiveness",
        ],
      },
    ],
    march: [
      {
        title: "Late Winter Assessment",
        description: "Check colony survival as temperatures begin to warm.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Wait for consistent 40°F (4°C) temperatures",
          "Check for live bees and food stores",
          "Begin feeding if stores are low",
          "Plan for April-May first inspection",
          "Assess winter losses",
        ],
      },
    ],
    april: [
      {
        title: "Pre-Spring Preparation",
        description: "Prepare for late spring start.",
        difficulty: "beginner",
        timeEstimate: "1-2 hours per apiary",
        tips: [
          "Clean bottom boards",
          "Remove winter wraps gradually",
          "Prepare feeding equipment",
          "Monitor for late frosts",
          "Check for queen and brood",
        ],
      },
    ],
    may: [
      {
        title: "First Spring Inspection",
        description: "Begin active beekeeping season.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Check for queen and brood",
          "Assess food stores",
          "Begin stimulative feeding",
          "Add second brood box if needed",
          "Begin varroa monitoring",
        ],
      },
      {
        title: "Install New Bees",
        description: "Install packages or nucs.",
        difficulty: "beginner",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Install on warm, calm days",
          "Provide immediate feeding",
          "Check for queen acceptance",
          "Monitor for 7-10 days",
          "Plan for winter from day one",
        ],
      },
    ],
    june: [
      {
        title: "Colony Building",
        description: "Support rapid colony development.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor brood pattern",
          "Add honey supers early",
          "Check for queen cells",
          "Begin swarm prevention",
          "Assess colony strength",
        ],
      },
      {
        title: "Advanced Mite Management",
        description: "Implement comprehensive varroa control program.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Test for varroa mites monthly",
          "Implement treatment rotation",
          "Monitor treatment effectiveness",
          "Plan for fall treatment",
          "Document mite levels",
        ],
      },
    ],
    july: [
      {
        title: "Peak Season Management",
        description: "Manage honey production and prevent swarming.",
        difficulty: "beginner",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Add supers as needed",
          "Check for queen cells weekly",
          "Monitor honey flow",
          "Ensure adequate ventilation",
          "Check water availability",
        ],
      },
      {
        title: "Advanced Swarm Management",
        description: "Implement advanced swarm prevention techniques.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Consider making splits",
          "Implement queen rearing",
          "Monitor colony balance",
          "Plan for fall requeening",
          "Document queen performance",
        ],
      },
    ],
    august: [
      {
        title: "Honey Harvest & Winter Prep",
        description: "Harvest honey and begin winter preparation.",
        difficulty: "beginner",
        timeEstimate: "1 hour per hive",
        tips: [
          "Harvest honey when capped",
          "Leave adequate stores (80-100 lbs)",
          "Begin winter preparation",
          "Assess colony strength",
          "Check queen status",
        ],
      },
      {
        title: "Advanced Varroa Treatment",
        description: "Implement fall varroa treatment program.",
        difficulty: "intermediate",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Treat for varroa mites",
          "Test treatment effectiveness",
          "Plan winter treatment schedule",
          "Document treatment history",
          "Monitor for resistance",
        ],
      },
    ],
    september: [
      {
        title: "Critical Winter Preparation",
        description: "Prepare colonies for harsh winter survival.",
        difficulty: "beginner",
        timeEstimate: "1 hour per hive",
        tips: [
          "Ensure adequate honey stores (80-100 lbs)",
          "Reduce hive entrances",
          "Add mouse guards",
          "Check queen status",
          "Assess colony strength for winter",
        ],
      },
      {
        title: "Advanced Winter Planning",
        description: "Implement advanced winter preparation strategies.",
        difficulty: "intermediate",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Plan winter protection strategy",
          "Assess colony combining needs",
          "Prepare emergency feeding plan",
          "Document winter preparation",
          "Plan for spring expansion",
        ],
      },
    ],
    october: [
      {
        title: "Final Winter Prep & Mite Treatment",
        description: "Complete winter preparations and final mite treatment.",
        difficulty: "beginner",
        timeEstimate: "1 hour per hive",
        tips: [
          "Remove excess supers",
          "Add insulation if needed",
          "Secure hives from wind",
          "Final varroa treatment on warm day",
          "Prepare winter protection supplies",
        ],
      },
      {
        title: "Advanced Fall Management",
        description: "Implement advanced fall management techniques.",
        difficulty: "intermediate",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Implement fall feeding program",
          "Plan winter monitoring schedule",
          "Prepare emergency protocols",
          "Document fall management",
          "Plan for next season",
        ],
      },
    ],
    november: [
      {
        title: "Winter Setup & Monitoring",
        description: "Complete winter setup and begin monitoring.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per apiary",
        tips: [
          "Clear entrances of debris",
          "Monitor for mice",
          "Ensure wind protection",
          "Check cluster position",
          "Plan for spring",
        ],
      },
      {
        title: "Winter Protection Application",
        description: "Apply winter protection before deep cold sets in.",
        difficulty: "intermediate",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Apply winter wraps or insulation",
          "Set up wind breaks",
          "Secure hives from wind",
          "Check hive weight",
          "Listen for buzzing",
        ],
      },
      
    ],
    december: [
      {
        title: "Winter Monitoring",
        description: "Minimal monitoring during deep winter.",
        difficulty: "beginner",
        timeEstimate: "15 minutes per apiary",
        tips: [
          "Check only on warm days",
          "Listen for colony activity",
          "Clear snow from entrances",
          "Plan for spring",
          "Monitor wind protection",
        ],
      },
      {
        title: "Winter Mite Treatment (Oxalic Acid)",
        description: "Treat for varroa mites monthly using oxalic acid vaporization.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Only use oxalic acid vaporization",
          "Treat on days above 35°F (2°C)",
          "Do not open hive - use vaporizer",
          "Follow safety protocols",
          "Monitor treatment effectiveness",
        ],
      },
    ],
  },
  "4b": {
    january: [
      {
        title: "Deep Winter Management",
        description: "Bees are in tight cluster. Minimal disturbance required.",
        difficulty: "beginner",
        timeEstimate: "15 minutes per apiary",
        tips: [
          "Only check on days above 25°F (-4°C)",
          "Listen for buzzing without opening hive",
          "Clear snow from entrances",
          "Check hive weight by lifting back corner",
          "Monitor for wind protection",
        ],
      },
      {
        title: "Equipment Preparation",
        description: "Prepare equipment for spring while bees are dormant.",
        difficulty: "beginner",
        timeEstimate: "2-3 hours per week",
        tips: [
          "Clean and repair equipment in heated space",
          "Order replacement parts early",
          "Build new equipment if needed",
          "Plan for late spring start (May-June)",
          "Prepare winter wraps for next season",
        ],
      },
      {
        title: "Winter Mite Treatment (Oxalic Acid)",
        description: "Treat for varroa mites using oxalic acid vaporization.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Only use oxalic acid vaporization",
          "Treat on days above 35°F (2°C)",
          "Do not open hive - use vaporizer",
          "Follow safety protocols",
          "Monitor treatment effectiveness",
        ],
      },
    ],
    february: [
      {
        title: "Emergency Feeding Check",
        description: "Monitor food stores during coldest period.",
        difficulty: "beginner",
        timeEstimate: "20 minutes per hive",
        tips: [
          "Check only on days above 25°F (-4°C)",
          "Use fondant or winter patties if needed",
          "Avoid liquid feeding in extreme cold",
          "Monitor for starvation signs",
          "Check cluster position",
        ],
      },
      {
        title: "Order Bees & Supplies",
        description: "Order bees for late spring arrival.",
        difficulty: "beginner",
        timeEstimate: "1-2 hours",
        tips: [
          "Order packages/nucs for May-June delivery",
          "Plan for short but intense season",
          "Order extra honey supers",
          "Consider local suppliers for hardier stock",
          "Order winter protection supplies early",
        ],
      },
      {
        title: "Winter Mite Treatment (Oxalic Acid)",
        description: "Treat for varroa mites using oxalic acid vaporization.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Only use oxalic acid vaporization",
          "Treat on days above 35°F (2°C)",
          "Do not open hive - use vaporizer",
          "Follow safety protocols",
          "Monitor treatment effectiveness",
        ],
      },
    ],
    march: [
      {
        title: "Late Winter Assessment",
        description: "Check colony survival as temperatures begin to warm.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Wait for consistent 40°F (4°C) temperatures",
          "Check for live bees and food stores",
          "Begin feeding if stores are low",
          "Plan for April-May first inspection",
          "Assess winter losses",
        ],
      },
    ],
    april: [
      {
        title: "Pre-Spring Preparation",
        description: "Prepare for late spring start.",
        difficulty: "beginner",
        timeEstimate: "1-2 hours per apiary",
        tips: [
          "Clean bottom boards",
          "Remove winter wraps gradually",
          "Prepare feeding equipment",
          "Monitor for late frosts",
          "Check for queen and brood",
        ],
      },
    ],
    may: [
      {
        title: "First Spring Inspection",
        description: "Begin active beekeeping season.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Check for queen and brood",
          "Assess food stores",
          "Begin stimulative feeding (pollen patties, thin syrup, etc.)",
          "Add second brood box if needed",
          "Begin varroa monitoring",
        ],
      },
      {
        title: "Install New Bees",
        description: "Install packages or nucs.",
        difficulty: "beginner",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Install on warm, calm days",
          "Provide immediate feeding",
          "Check for queen acceptance",
          "Monitor for 7-10 days",
          "Plan for winter from day one",
        ],
      },
    ],
    june: [
      {
        title: "Colony Building",
        description: "Support rapid colony development.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor brood pattern",
          "Add honey supers early",
          "Check for queen cells",
          "Begin swarm prevention",
          "Assess colony strength",
        ],
      },
      {
        title: "Advanced Mite Management",
        description: "Implement comprehensive varroa control program.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Test for varroa mites monthly",
          "Implement treatment rotation",
          "Monitor treatment effectiveness",
          "Plan for fall treatment",
          "Document mite levels",
        ],
      },
    ],
    july: [
      {
        title: "Peak Season Management",
        description: "Manage honey production and prevent swarming.",
        difficulty: "beginner",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Add supers as needed",
          "Check for queen cells weekly",
          "Monitor honey flow",
          "Ensure adequate ventilation",
          "Check water availability",
        ],
      },
      {
        title: "Advanced Swarm Management",
        description: "Implement advanced swarm prevention techniques.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Consider making splits",
          "Implement queen rearing",
          "Monitor colony balance",
          "Plan for fall requeening",
          "Document queen performance",
        ],
      },
    ],
    august: [
      {
        title: "Honey Harvest & Winter Prep",
        description: "Harvest honey and begin winter preparation.",
        difficulty: "beginner",
        timeEstimate: "1 hour per hive",
        tips: [
          "Harvest honey when capped",
          "Leave adequate stores (80-100 lbs)",
          "Begin winter preparation",
          "Assess colony strength",
          "Check queen status",
        ],
      },
      {
        title: "Advanced Varroa Treatment",
        description: "Implement fall varroa treatment program.",
        difficulty: "intermediate",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Treat for varroa mites",
          "Test treatment effectiveness",
          "Plan winter treatment schedule",
          "Document treatment history",
          "Monitor for resistance",
        ],
      },
    ],
    september: [
      {
        title: "Critical Winter Preparation",
        description: "Prepare colonies for harsh winter survival.",
        difficulty: "beginner",
        timeEstimate: "1 hour per hive",
        tips: [
          "Ensure adequate honey stores (80-100 lbs)",
          "Reduce hive entrances",
          "Add mouse guards",
          "Check queen status",
          "Assess colony strength for winter",
        ],
      },
      {
        title: "Advanced Winter Planning",
        description: "Implement advanced winter preparation strategies.",
        difficulty: "intermediate",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Plan winter protection strategy",
          "Assess colony combining needs",
          "Prepare emergency feeding plan",
          "Document winter preparation",
          "Plan for spring expansion",
        ],
      },
    ],
    october: [
      {
        title: "Final Winter Prep & Mite Treatment",
        description: "Complete winter preparations and final mite treatment.",
        difficulty: "beginner",
        timeEstimate: "1 hour per hive",
        tips: [
          "Remove excess supers",
          "Add insulation if needed",
          "Secure hives from wind",
          "Final varroa treatment on warm day",
          "Prepare winter protection supplies",
        ],
      },
      {
        title: "Advanced Fall Management",
        description: "Implement advanced fall management techniques.",
        difficulty: "intermediate",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Implement fall feeding program",
          "Plan winter monitoring schedule",
          "Prepare emergency protocols",
          "Document fall management",
          "Plan for next season",
        ],
      },
    ],
    november: [
      {
        title: "Winter Protection Application",
        description: "Apply winter protection before deep cold sets in.",
        difficulty: "intermediate",
        timeEstimate: "45 minutes per hive",
        tips: [
          "Apply winter wraps or insulation",
          "Set up wind breaks",
          "Secure hives from wind",
          "Check hive weight",
          "Listen for buzzing",
        ],
      },
      {
        title: "Winter Setup & Monitoring",
        description: "Complete winter setup and begin monitoring.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per apiary",
        tips: [
          "Clear entrances of debris",
          "Monitor for mice",
          "Ensure wind protection",
          "Check cluster position",
          "Plan for spring",
        ],
      },
    ],
    december: [
      {
        title: "Winter Monitoring",
        description: "Minimal monitoring during deep winter.",
        difficulty: "beginner",
        timeEstimate: "15 minutes per apiary",
        tips: [
          "Check only on warm days",
          "Listen for colony activity",
          "Clear snow from entrances",
          "Plan for spring",
          "Monitor wind protection",
        ],
      },
      {
        title: "Winter Mite Treatment (Oxalic Acid)",
        description: "Treat for varroa mites using oxalic acid vaporization.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Only use oxalic acid vaporization",
          "Treat on days above 35°F (2°C)",
          "Do not open hive - use vaporizer",
          "Follow safety protocols",
          "Monitor treatment effectiveness",
        ],
      },
    ],
  },
  "10a": {
    january: [
      {
        title: "Year-Round Management",
        description: "Bees remain active year-round in subtropical climate.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor for continuous brood production",
          "Check for year-round honey flow",
          "Manage varroa mites year-round",
          "Plan for multiple honey harvests",
        ],
      },
      {
        title: "Equipment Preparation",
        description: "Prepare equipment for peak season.",
        difficulty: "beginner",
        timeEstimate: "2-3 hours per week",
        tips: [
          "Clean and repair equipment",
          "Order replacement parts early",
          "Build new equipment if needed",
          "Plan for early spring expansion",
        ],
      },
    ],
    february: [
      {
        title: "Early Spring Management",
        description: "Begin active beekeeping season in subtropical climate.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Check for queen and brood production",
          "Assess food stores and begin feeding if needed",
          "Add honey supers early for spring flow",
          "Monitor for swarm preparations",
        ],
      },
      {
        title: "Order Bees & Supplies",
        description: "Order bees for early spring arrival.",
        difficulty: "beginner",
        timeEstimate: "1-2 hours",
        tips: [
          "Order packages/nucs for February-March delivery",
          "Plan for extended season with multiple flows",
          "Order extra honey supers for multiple harvests",
          "Consider local suppliers adapted to subtropical climate",
        ],
      },
    ],
    march: [
      {
        title: "Peak Spring Management",
        description: "Manage colonies during peak spring activity.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor rapid colony expansion",
          "Add honey supers as needed",
          "Check for queen cells and swarm prevention",
          "Begin varroa mite monitoring",
        ],
      },
    ],
    april: [
      {
        title: "Spring Honey Harvest",
        description: "Harvest spring honey crop.",
        difficulty: "intermediate",
        timeEstimate: "1 hour per hive",
        tips: [
          "Harvest spring honey when capped",
          "Leave adequate stores for summer",
          "Treat for varroa mites",
          "Prepare for summer management",
        ],
      },
    ],
    may: [
      {
        title: "Summer Preparation",
        description: "Prepare for hot summer months.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Ensure adequate ventilation",
          "Provide water sources",
          "Monitor for heat stress",
          "Check for small hive beetles",
        ],
      },
    ],
    june: [
      {
        title: "Summer Management",
        description: "Manage colonies during hot summer.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor for heat stress",
          "Check water availability",
          "Manage varroa mites",
          "Watch for robbing behavior",
        ],
      },
    ],
    july: [
      {
        title: "Summer Harvest",
        description: "Harvest summer honey crop.",
        difficulty: "intermediate",
        timeEstimate: "1 hour per hive",
        tips: [
          "Harvest summer honey when capped",
          "Leave adequate stores for fall",
          "Treat for varroa mites",
          "Prepare for fall management",
        ],
      },
    ],
    august: [
      {
        title: "Fall Preparation",
        description: "Prepare for fall nectar flows.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Add supers for fall flow",
          "Monitor colony strength",
          "Check for queen cells",
          "Begin fall feeding if needed",
        ],
      },
    ],
    september: [
      {
        title: "Fall Management",
        description: "Manage colonies during fall flows.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor fall nectar flow",
          "Add supers as needed",
          "Check for queen cells",
          "Begin winter preparation",
        ],
      },
    ],
    october: [
      {
        title: "Fall Harvest",
        description: "Harvest fall honey crop.",
        difficulty: "intermediate",
        timeEstimate: "1 hour per hive",
        tips: [
          "Harvest fall honey when capped",
          "Leave adequate stores for winter",
          "Treat for varroa mites",
          "Complete winter preparation",
        ],
      },
    ],
    november: [
      {
        title: "Winter Preparation",
        description: "Prepare for mild winter.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Ensure adequate honey stores",
          "Reduce hive entrances",
          "Add mouse guards",
          "Check queen status",
        ],
      },
    ],
    december: [
      {
        title: "Winter Management",
        description: "Manage colonies during mild winter.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor colony activity",
          "Check food stores",
          "Manage varroa mites",
          "Plan for early spring",
        ],
      },
    ],
  },
  "13b": {
    january: [
      {
        title: "Year-Round Management",
        description: "Bees remain active year-round in tropical climate.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor for year-round brood production",
          "Check for continuous honey flow",
          "Manage varroa mites year-round",
          "Plan for multiple honey harvests",
        ],
      },
    ],
    february: [
      {
        title: "Peak Season Management",
        description: "Manage colonies during peak tropical season.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor rapid colony expansion",
          "Add honey supers as needed",
          "Check for queen cells and swarm prevention",
          "Begin varroa mite monitoring",
        ],
      },
    ],
    march: [
      {
        title: "Honey Harvest",
        description: "Harvest tropical honey crop.",
        difficulty: "intermediate",
        timeEstimate: "1 hour per hive",
        tips: [
          "Harvest honey when capped",
          "Leave adequate stores for colony",
          "Treat for varroa mites",
          "Prepare for next flow",
        ],
      },
    ],
    april: [
      {
        title: "Colony Management",
        description: "Manage colonies during tropical season.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor colony strength",
          "Add supers as needed",
          "Check for queen cells",
          "Manage varroa mites",
        ],
      },
    ],
    may: [
      {
        title: "Tropical Management",
        description: "Manage colonies in tropical climate.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor for heat stress",
          "Ensure adequate ventilation",
          "Check for small hive beetles",
          "Manage varroa mites",
        ],
      },
    ],
    june: [
      {
        title: "Summer Management",
        description: "Manage colonies during tropical summer.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor for heat stress",
          "Check water availability",
          "Manage varroa mites",
          "Watch for robbing behavior",
        ],
      },
    ],
    july: [
      {
        title: "Tropical Harvest",
        description: "Harvest tropical honey crop.",
        difficulty: "intermediate",
        timeEstimate: "1 hour per hive",
        tips: [
          "Harvest honey when capped",
          "Leave adequate stores for colony",
          "Treat for varroa mites",
          "Prepare for next flow",
        ],
      },
    ],
    august: [
      {
        title: "Colony Management",
        description: "Manage colonies during tropical season.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor colony strength",
          "Add supers as needed",
          "Check for queen cells",
          "Manage varroa mites",
        ],
      },
    ],
    september: [
      {
        title: "Tropical Management",
        description: "Manage colonies in tropical climate.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor for heat stress",
          "Ensure adequate ventilation",
          "Check for small hive beetles",
          "Manage varroa mites",
        ],
      },
    ],
    october: [
      {
        title: "Tropical Harvest",
        description: "Harvest tropical honey crop.",
        difficulty: "intermediate",
        timeEstimate: "1 hour per hive",
        tips: [
          "Harvest honey when capped",
          "Leave adequate stores for colony",
          "Treat for varroa mites",
          "Prepare for next flow",
        ],
      },
    ],
    november: [
      {
        title: "Colony Management",
        description: "Manage colonies during tropical season.",
        difficulty: "intermediate",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor colony strength",
          "Add supers as needed",
          "Check for queen cells",
          "Manage varroa mites",
        ],
      },
    ],
    december: [
      {
        title: "Year-Round Management",
        description: "Bees remain active year-round in tropical climate.",
        difficulty: "beginner",
        timeEstimate: "30 minutes per hive",
        tips: [
          "Monitor for year-round brood production",
          "Check for continuous honey flow",
          "Manage varroa mites year-round",
          "Plan for multiple honey harvests",
        ],
      },
    ],
  },
};
