export const regions = [
  { value: "3a", label: "Zone 3a - Very Cold (Northern Canada, Alaska)" },
  { value: "3b", label: "Zone 3b - Very Cold (Northern US, Canada)" },
  { value: "4a", label: "Zone 4a - Cold (Upper Midwest, Northern New England)" },
  { value: "4b", label: "Zone 4b - Cold (Upper Midwest, Northern Plains)" },
  { value: "5a", label: "Zone 5a - Cool (Midwest, Northern Appalachians)" },
  { value: "5b", label: "Zone 5b - Cool (Midwest, Central Appalachians)" },
  { value: "6a", label: "Zone 6a - Moderate (Mid-Atlantic, Central Midwest)" },
  { value: "6b", label: "Zone 6b - Moderate (Mid-Atlantic, Southern Midwest)" },
  { value: "7a", label: "Zone 7a - Mild (Southeast, Southern Midwest)" },
  { value: "7b", label: "Zone 7b - Mild (Southeast, Southern Plains)" },
  { value: "8a", label: "Zone 8a - Warm (Deep South, Southern California)" },
  { value: "8b", label: "Zone 8b - Warm (Deep South, Coastal California)" },
  { value: "9a", label: "Zone 9a - Warm (North Florida, South Georgia, Coastal Texas)" },
  { value: "9b", label: "Zone 9b - Warm (North Florida, South Georgia, Coastal Texas)" },
  { value: "10a", label: "Zone 10a - Very Hot (Southern Florida, Hawaii)" },
  { value: "10b", label: "Zone 10b - Very Hot (Southern Florida, Hawaii)" },
  { value: "11a", label: "Zone 11a - Tropical (Hawaii, Puerto Rico)" },
  { value: "11b", label: "Zone 11b - Tropical (Hawaii, Puerto Rico)" },
  { value: "12a", label: "Zone 12a - Tropical (Hawaii, Puerto Rico)" },
  { value: "12b", label: "Zone 12b - Tropical (Hawaii, Puerto Rico)" },
  { value: "13a", label: "Zone 13a - Tropical (Hawaii, Puerto Rico)" },
  { value: "13b", label: "Zone 13b - Tropical (Hawaii, Puerto Rico)" },
];
